language: erlang
otp_release:
  - 19.0
  - 18.0
script:  "rm -rf .git && make tests"
addons:
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y consul
  - sudo apt-get install -y etcd
  - sleep 2
