language: erlang
otp_release:
  - 19.0
  - 18.0
script:  "rm -rf .git && make tests"
addons:
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  - sudo apt-get update -q
  - sudo apt-get install -y consul
  - sudo apt-get install -y etcd
  - sleep 2
